server {
    listen 8080;
    server_name localhost;

    location /beauty.ai/ {
        alias /usr/share/nginx/html/beauty.ai/;
        index index.html index.htm;
        try_files $uri $uri/ /beauty.ai/index.html;
    }

    location / {
        return 301 $scheme://$http_host/beauty.ai/;
    }
}