# Generated by Django 6.0.7 on 2026-07-26 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("users", "0003_user_phone_master_masterservice_master_services_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="master_appointments",
                to="users.master",
            ),
        ),
    ]
