# Generated by Django 6.0.7 on 2026-08-06 08:51

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('beauty_service', '0001_initial'),
        ('salons', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='appointments_check',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 6, 8, 51, 1, 540763, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 6, 8, 51, 44, 229044, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='appointments_check'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
