redis:
  replicaCount: 2
  namespace: beauty-dev

postgres:
  replicaCount: 1
  namespace: beauty-dev
  
  secrets:
    POSTGRES_DB: placeholder
    POSTGRES_USER: placeholder
    POSTGRES_PASSWORD: placeholder

common:
  namespace: beauty-dev
  environment: development

replicaCount: 2


#DEVELOPMENT ADDITIONAL CONFIGS AND SECRETS
config: 
  TESTING: true

secrets:
  DJANGO_SECRET_KEY: placeholder
  GOOGLE_CLIENT_ID: placeholder
  EMAIL_HOST_USER: placeholder
  EMAIL_HOST_PASSWORD: placeholder
  GEOAPIFY_API_KEY: placeholder
  POSTGRES_DB: placeholder
  POSTGRES_USER: placeholder
  POSTGRES_PASSWORD: placeholder
  POSTGRES_HOST: placeholder
  POSTGRES_PORT: placeholder