redis:
  replicaCount: 2
  namespace: beauty-dev

postgres:
  replicaCount: 1
  namespace: beauty-dev
  
  secrets:
    POSTGRES_DB: beautydb
    POSTGRES_USER: igoryok
    POSTGRES_PASSWORD: KB24lapassDb!09

common:
  namespace: beauty-dev
  environment: development

replicaCount: 2


#DEVELOPMENT ADDITIONAL CONFIGS AND SECRETS
config: 
  TESTING: true

secrets:
  DJANGO_SECRET_KEY: django-insecure-hl%3e)9_(s9ku@k4to7jo7=t1@ae4-4%9jgku*!+ywzt*q)*y(
  GOOGLE_CLIENT_ID: 136485800268-6lrfcd7uh3g14jhaspul8k2n8rpnm8o6.apps.googleusercontent.com
  EMAIL_HOST_USER: kluzodota@gmail.com
  EMAIL_HOST_PASSWORD: toceobwjqnzydznm
  GEOAPIFY_API_KEY: a7580c03d6a343c1871c71c76d55f16c
  POSTGRES_DB: beautydb
  POSTGRES_USER: igoryok
  POSTGRES_PASSWORD: KB24lapassDb!09
  POSTGRES_HOST: postgres-0.postgres
  POSTGRES_PORT: "5432"