apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beauty-back.fullname" . }}-secrets
  namespace: {{ .Values.common.namespace }} 
type: Opaque
data:
{{- range $key, $val := .Values.secrets }}
    {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}