# Generated by Django 6.0.7 on 2026-07-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
