# Generated by Django 6.0.7 on 2026-08-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='master',
        ),
    ]
