# Generated by Django 6.0.7 on 2026-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("district", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("opened_date", models.DateField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "db_table": "salons",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "address"), name="unique_salon_name_address"
                    )
                ],
            },
        ),
    ]
