# Generated by Django 6.0.7 on 2026-07-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedsalon',
            name='external_booking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='external_booking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
