# Generated by Django 6.0.7 on 2026-07-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_initial'),
        ('users', '0002_user_birth_date_user_gender_user_last_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='masters',
            field=models.ManyToManyField(related_name='salons', to='users.master'),
        ),
    ]
