apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.common.namespace }}
data:
  BACKEND_URL: {{ .Values.frontend.config.backend_url | quote }}
  TZ: {{ .Values.frontend.config.time_zone | quote }}
