# Generated by Django 6.0.7 on 2026-07-29 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beauty_service', '0001_initial'),
        ('salons', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=120)),
                ('destination_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_events', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_events', to='salons.salon')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_events', to='beauty_service.service')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='referral_ev_created_f66bda_idx'), models.Index(fields=['session_id'], name='referral_ev_session_e0af96_idx'), models.Index(fields=['event_type'], name='referral_ev_event_t_16e0a9_idx'), models.Index(fields=['salon'], name='referral_ev_salon_i_494554_idx'), models.Index(fields=['service'], name='referral_ev_service_b15336_idx'), models.Index(fields=['salon', 'created_at'], name='referral_ev_salon_i_f67d49_idx')],
            },
        ),
    ]
