# Generated by Django 6.0.7 on 2026-07-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_salons',
            field=models.ManyToManyField(blank=True, related_name='followers', to='salons.salon'),
        ),
    ]
