# Generated by Django 6.0.7 on 2026-07-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingschedule',
            name='is_day_off',
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='is_working_day',
            field=models.BooleanField(default=True),
        ),
    ]
