# Generated by Django 6.0.7 on 2026-07-26 13:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_service', '0001_initial'),
        ('users', '0002_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='users.master')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='beauty_service.service')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='masters', through='users.MasterService', to='beauty_service.service'),
        ),
        migrations.AddConstraint(
            model_name='masterservice',
            constraint=models.UniqueConstraint(fields=('master', 'service'), name='unique_master_service'),
        ),
    ]
