name: Backend CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  DockerImageName: beauty-backend
jobs:
  django-ci:
    name: build and test django app
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        python-version: ["3.13"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1
      
    - name: Setup python-${{ matrix.python-version }} 
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install -r requirements.txt
        
    - name: Testing frontend
      run: echo "Passing all types of tests"

    - name: Linting
      run: |
        flake8 . --show-source --statistics --exit-zero

    - name: Check Complexity
      run: |
        flake8 . --max-complexity=6 --exit-zero
        
    - name: Upload helm artifacts
      uses: actions/upload-artifact@v4
      with:
        name: helm-artifacts
        path: ${{ github.workspace }}/helm-charts

  docker-ci:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: django-ci
    environment: development
    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push image
      uses: docker/build-push-action@v7
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DockerImageName }}:1.0.${{ github.run_number }}
        
  helm-ci:
    name: Helm-chart CI
    needs: django-ci
    runs-on: ubuntu-latest
    environment: development
    steps:
    
    - name: Upload helm chart
      uses: actions/download-artifact@v4
      with:
        name: helm-artifacts
        path: .
    
    - name: Set Up Helm
      uses: azure/setup-helm@v5
    
    - name: Lint helm
      run: helm lint ./beauty-back

    - name: Template Helm
      run: helm template beautyfront ./beauty-back

  
  deploying:
    environment: development
    name: Deploy to development env
    needs: [docker-ci, helm-ci]  # DON'T FORGET TO ADD DOCKER CI 
    runs-on: ubuntu-latest

    steps:
    - name: Upload helm chart
      uses: actions/download-artifact@v4
      with:
        name: helm-artifacts
        path: .
    
    - name: add_key
      run: | 
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        ssh-keyscan -H "${{ vars.API_CLUSTER_HOST }}" >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
             
    - name: copy package to VM
      run: scp -i ~/.ssh/id_ed25519 -r beauty-back developer@${{ vars.API_CLUSTER_HOST }}:/home/developer/

    - name: helm --dry-run
      run: |
       ssh -i ~/.ssh/id_ed25519 developer@${{ vars.API_CLUSTER_HOST }} "helm upgrade --install beauty-back beauty-back/ -f beauty-back/values/values-dev.yaml --dry-run \
          --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DockerImageName }} \
          --set image.tag=1.0.${{ github.run_number }}" \
          --set postgres.secrets.POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          --set postgres.secrets.POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          --set postgres.secrets.POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          --set secrets.DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} \
          --set secrets.GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID}} \
          --set secrets.EMAIL_HOST_USER \
          --set secrets.EMAIL_HOST_PASSWORD \
          --set secrets.GEOAPIFY_API_KEY \
          --set secrets.POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          --set secrets.POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          --set secrets.POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          --set secrets.POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}\
          --set secrets.POSTGRES_PORT=${{ secrets.POSTGRES_PORT}}

    - name: Deploy Helm to cluster
      run: |
        ssh -i ~/.ssh/id_ed25519 developer@${{ vars.API_CLUSTER_HOST }} "helm upgrade --install beauty-back beauty-back/ -f beauty-back/values/values-dev.yaml \
          --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DockerImageName }} \
          --set image.tag=1.0.${{ github.run_number }}" \
          --set postgres.secrets.POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          --set postgres.secrets.POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          --set postgres.secrets.POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          --set secrets.DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} \
          --set secrets.GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID}} \
          --set secrets.EMAIL_HOST_USER \
          --set secrets.EMAIL_HOST_PASSWORD \
          --set secrets.GEOAPIFY_API_KEY \
          --set secrets.POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          --set secrets.POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          --set secrets.POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          --set secrets.POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}\
          --set secrets.POSTGRES_PORT=${{ secrets.POSTGRES_PORT}}"
