name: helm-uprade
run-name: ${{ github.actor }} - ${{ github.ref_name }}

on: 
  workflow_call: 
    inputs:
      environment:
        required: true
        description: "Environment to deploy to"
        type: string
      version:
        required: true
        type: string
      helm-values-path:
        type: string
        default: "./beauty-back/values/values-dev.yaml"
      helm-release-name:
        type: string
        default: "beauty-back"

env: 
  DockerImageName: beauty-backend

jobs: 

  deploy-helm:
    name: Deploying with helm to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    env:
      namespace: ${{ inputs.environment == 'development' && 'beauty-dev' || 'beauty-prod'}}
    steps:
    - name: Upload helm chart
      uses: actions/download-artifact@v4
      with:
        name: helm-artifacts
        path: .
    
    - name: add_key
      run: | 
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        ssh-keyscan -H "${{ vars.API_CLUSTER_HOST }}" >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
             
    - name: copy package to VM
      run: scp -i ~/.ssh/id_ed25519 -r beauty-back developer@${{ vars.API_CLUSTER_HOST }}:/home/developer/
      
    - name: helm --dry-run
      run: |
        ssh -i ~/.ssh/id_ed25519 developer@${{ vars.API_CLUSTER_HOST }} "helm upgrade --install ${{ inputs.helm-release-name }} beauty-back/ -f ${{ inputs.helm-values-path}} --dry-run \
          --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DockerImageName }} \
          --set image.tag=1.0.${{ github.run_number }} "
          
    - name: Deploy Helm to ${{ inputs.environment }}
      run: |
         ssh -i ~/.ssh/id_ed25519 developer@${{ vars.API_CLUSTER_HOST }} "helm upgrade --install --atomic --wait --timeout 600s --debug ${{ inputs.helm-release-name }} beauty-back/ -f ${{ inputs.helm-values-path}} \
          -f ${{ inputs.helm-values-path }} \
          -n ${{env.namespace}} \
          --create-namespace \
          --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DockerImageName }} \
          --set image.tag=1.0.${{ github.run_number }} \
          --set-string postgres.secrets.POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          --set-string postgres.secrets.POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          --set-string postgres.secrets.POSTGRES_PASSWORD=\"${{ secrets.POSTGRES_PASSWORD }}\" \
          --set-string secrets.DJANGO_SECRET_KEY=\"${{ secrets.DJANGO_SECRET_KEY }}\" \
          --set-string secrets.GOOGLE_CLIENT_ID=\"${{ secrets.GOOGLE_CLIENT_ID}}\" \
          --set-string secrets.EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER}} \
          --set-string secrets.EMAIL_HOST_PASSWORD=\"${{ secrets.EMAIL_HOST_PASSWORD}}\" \
          --set-string secrets.GEOAPIFY_API_KEY=${{ secrets.GEOAPIFY_API_KEY}} \
          --set-string secrets.POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          --set-string secrets.POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          --set-string secrets.POSTGRES_PASSWORD=\"${{ secrets.POSTGRES_PASSWORD }}\" \
          --set-string secrets.POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}\
          --set-string secrets.POSTGRES_PORT=${{ secrets.POSTGRES_PORT}}"

